-- MySQL Script generated by MySQL Workbench
-- Tue Feb 20 13:56:46 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb_ponche
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb_ponche
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb_ponche` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `mydb_ponche` ;

-- -----------------------------------------------------
-- Table `mydb_ponche`.`tb_perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_ponche`.`tb_perfil` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `status` ENUM('0', '1') NOT NULL DEFAULT '1',
  `cadastro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_ponche`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_ponche`.`tb_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `perfil_id` INT NOT NULL,
  `cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `dataAcesso` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` ENUM('0', '1') NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_usuario_perfil1_idx` (`perfil_id` ASC),
  CONSTRAINT `fk_usuario_perfil1`
    FOREIGN KEY (`perfil_id`)
    REFERENCES `mydb_ponche`.`tb_perfil` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_ponche`.`tb_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_ponche`.`tb_tipo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `usuario_id` INT NOT NULL,
  `cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` ENUM('0', '1') NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  INDEX `fk_tipo_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_tipo_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb_ponche`.`tb_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_ponche`.`tb_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_ponche`.`tb_categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` ENUM('0', '1') NOT NULL DEFAULT '1',
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_categoria_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_categoria_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb_ponche`.`tb_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_ponche`.`tb_subcategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_ponche`.`tb_subcategoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `categoria_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` ENUM('0', '1') NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_subCategoria_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_subCategoria_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb_ponche`.`tb_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_ponche`.`tb_conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_ponche`.`tb_conta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(100) NULL,
  `usuario_id` INT NOT NULL,
  `cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` ENUM('0', '1') NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Conta_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_Conta_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb_ponche`.`tb_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_ponche`.`tb_dependente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_ponche`.`tb_dependente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `usuario_id` INT NOT NULL,
  `cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` ENUM('0', '1') NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Dependente_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_Dependente_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb_ponche`.`tb_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_ponche`.`tb_movimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_ponche`.`tb_movimento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `valor` DOUBLE NOT NULL,
  `Conta_id` INT NOT NULL,
  `Tipo_id` INT NOT NULL,
  `subCategoria_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `Dependente_id` INT NULL,
  `cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` ENUM('0', '1') NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_lancamento_subCategoria1_idx` (`subCategoria_id` ASC),
  INDEX `fk_lancamento_Tipo1_idx` (`Tipo_id` ASC),
  INDEX `fk_lancamento_Conta1_idx` (`Conta_id` ASC),
  INDEX `fk_lancamento_Dependente1_idx` (`Dependente_id` ASC),
  INDEX `fk_movimento_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_lancamento_subCategoria1`
    FOREIGN KEY (`subCategoria_id`)
    REFERENCES `mydb_ponche`.`tb_subcategoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lancamento_Tipo1`
    FOREIGN KEY (`Tipo_id`)
    REFERENCES `mydb_ponche`.`tb_tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lancamento_Conta1`
    FOREIGN KEY (`Conta_id`)
    REFERENCES `mydb_ponche`.`tb_conta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lancamento_Dependente1`
    FOREIGN KEY (`Dependente_id`)
    REFERENCES `mydb_ponche`.`tb_dependente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimento_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb_ponche`.`tb_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb_ponche`.`tb_meta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_ponche`.`tb_meta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `titulo` VARCHAR(50) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `valortotal` DOUBLE NOT NULL,
  `inicio` DATE NOT NULL,
  `fim` DATE NOT NULL,
  `status` ENUM('0', '1') NOT NULL DEFAULT '1',
  `cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_meta_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_meta_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb_ponche`.`tb_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_ponche`.`tb_meta_detalhe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_ponche`.`tb_meta_detalhe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `meta_id` INT NOT NULL,
  `valor` DOUBLE NULL,
  `status` ENUM('0', '1') NOT NULL DEFAULT '1',
  `cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_tb_meta_detalhe_tb_meta1_idx` (`meta_id` ASC),
  CONSTRAINT `fk_tb_meta_detalhe_tb_meta1`
    FOREIGN KEY (`meta_id`)
    REFERENCES `mydb_ponche`.`tb_meta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_ponche`.`tb_movimento_detalhe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_ponche`.`tb_movimento_detalhe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `movimento_id` INT NOT NULL,
  `valor` DOUBLE NOT NULL,
  `pagamento` DATE NULL,
  `vencimento` DATE NULL,
  `quitado` ENUM('0', '1') NULL DEFAULT '0',
  `cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` ENUM('0', '1') NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_movimento_detalhe_movimento1_idx` (`movimento_id` ASC),
  CONSTRAINT `fk_movimento_detalhe_movimento1`
    FOREIGN KEY (`movimento_id`)
    REFERENCES `mydb_ponche`.`tb_movimento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

#insert
INSERT INTO tb_perfil (nome) VALUES ('Administrador'), ('Analista tecnico'), ('Usuario');

INSERT INTO tb_usuario (nome, email, senha, perfil_id) VALUES 
	('Administrador','admin@sistemaponche.com.br','admin',1),
    ('Analista tecnico','analista@sistemaponche.com.br','analista',2),
	('Usuario','usuario@sistemaponche.com.br','usuario',3);
    
INSERT INTO tb_dependente (nome, usuario_id) VALUES ('João Paulo',3);    
INSERT INTO tb_conta (nome, descricao, usuario_id) VALUES ('Carteira','Carteira',3);
INSERT INTO tb_tipo (nome, usuario_id) VALUES ('Entrada','1'),('Saida','1'),('Transferencia','1');

INSERT INTO tb_meta (usuario_id, titulo, descricao, valortotal, inicio, fim) VALUES (
	3,'Viagem de ferias','Viagem de ferias',900.00,'2018-12-01','2018-01-01');    

INSERT INTO tb_meta_detalhe (meta_id, valor) VALUES (1,300.00);

INSERT INTO tb_categoria (nome, descricao ,usuario_id) VALUES 
	('Moradia','Moradia','1'),('Alimentação','Alimentação','1'),('Saúde','Saúde','1'),
    ('Educação','Educação','1'),('Transporte','Transporte','1');
    
INSERT INTO tb_subcategoria (nome, categoria_id ,usuario_id) VALUES 
	('Prestação',1, 1), ('Aluguel',1, 1), ('Fatura de água',1, 1),('Fatura de luz',1, 1), ('Fatura de telefone/internet',1, 1),
	('Supermercado',2, 1),('Restaurante',2, 1),('Açougue',2, 1),    
    ('Médico',3, 1),('Dentista',3, 1),('Farmacia',3, 1),    
    ('Faculdade',4, 1),('Livro',4, 1),('Curso',4, 1),    
    ('Combustível',5, 1),('Corrida',5, 1),('Manutenção',5, 1);

INSERT INTO tb_movimento (
	descricao, valor, Conta_id, Tipo_id, subCategoria_id, usuario_id, Dependente_id) VALUES (
	'Conta de água', 49.99, 1, 2, 1, 3, NULL);
    
INSERT INTO tb_movimento_detalhe (
	movimento_id, valor,pagamento,vencimento, quitado) VALUES (
    1,49.99,'2018-01-01','2018-12-31','1');
